# Generated by Django 4.1.4 on 2023-02-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="name",
            field=models.CharField(default="test", max_length=100),
        ),
    ]
