# Generated by Django 4.1.4 on 2023-06-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_route_name"),
    ]

    operations = [
        migrations.RenameModel(old_name="Route", new_name="Shop",),
        migrations.RenameModel(old_name="FavouriteRoute", new_name="ShopFavourite",),
        migrations.RenameModel(old_name="RouteUpvote", new_name="ShopUpvote",),
    ]
