# Generated by Django 4.1.4 on 2023-06-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_route_shop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
