# Generated by Django 4.1.4 on 2023-06-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_shop_shop_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="shop", name="creator",),
        migrations.RemoveField(model_name="shop", name="timestamp",),
        migrations.AddField(
            model_name="shop",
            name="tags",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
