# Generated by Django 4.1.4 on 2023-06-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_reviews_delete_routecomment_shop_average_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="shop", name="distance",),
    ]
