# Generated by Django 4.1.4 on 2023-06-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_shop_distance"),
    ]

    operations = [
        migrations.DeleteModel(name="ShopFavourite",),
        migrations.RenameField(
            model_name="user", old_name="saved_shops", new_name="favourite_shop",
        ),
    ]
