# Generated by Django 4.1.4 on 2023-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="locations",
            name="street",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
